# Generated by Django 4.2 on 2023-05-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplines.disciplines', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность пользователя')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж')),
                ('education', models.CharField(max_length=200, verbose_name='Образование')),
                ('disciplines', models.ManyToManyField(through='users.DepartmentGroup', to='disciplines.disciplines')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='departmentgroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='AboutTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_info', models.CharField(choices=[('experience', 'Опыт работы'), ('achievement', 'Достижения'), ('talents', 'Таланты'), ('about_me', 'Обо мне')], max_length=100, verbose_name='Тип информации')),
                ('title', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(max_length=1000, verbose_name='Основные сведения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_teacher', to='users.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'type_info')},
            },
        ),
    ]
