# Generated by Django 4.2 on 2023-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('quote', models.CharField(max_length=255, null=True, verbose_name='Цитата или краткое описание для заголовка')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='Автор цитаты')),
                ('content', models.TextField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
